# Generated by Django 4.0.3 on 2022-03-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Nariai',
        ),
    ]
