# Generated by Django 4.0.3 on 2022-03-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nariai_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Member',
        ),
    ]
