# Generated by Django 4.0.3 on 2022-03-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_post_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Post',
        ),
    ]
